POST  http://localhost:3003/user
content-type: application/json

    {
        "name": "eliel" ,
        "cpf": 12345678998 ,
        "birthYear": 1984
    }

###

GET http://localhost:3003/user
content-type: application/json

###

GET http://localhost:3003/user/saldo
content-type: application/json
    
    { //?????? bugaado
        "name": "eliel",
        "cpf": 12345678998 
    }