POST http://localhost:3003/user/signup
Content-Type: application/json

{ 
   "email": "osbourne@oscorp.com" ,
   "password": "ihatepeter"
}
###

PUT http://localhost:3003/user/edit
Content-Type: application/json

{
   "name": "Harry Osbourne" 
}
###